import type { Metadata } from "next"

export const metadata: Metadata = { title: "Disclaimer · ZippyTales" }

export default function DisclaimerPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="text-3xl font-extrabold text-ink">Disclaimer</h1>
      <p className="mt-2 text-sm text-ink-muted">Last updated: June 2026</p>
      <div className="mt-8 space-y-6 text-ink-muted">
        <p>
          Stories generated by ZippyTales are created by an AI model and are for
          entertainment purposes only. We apply safety guidelines to keep
          content age-appropriate, but AI output can occasionally be imperfect or
          unexpected.
        </p>
        <p>
          Please review stories before sharing them with a child, and keep young
          children supervised while reading. ZippyTales is not a substitute for
          professional or educational advice.
        </p>
      </div>
    </main>
  )
}
