export default function DisclaimerPage() {
  return (
    <main className="mx-auto max-w-3xl px-8 py-16">
      <h1 className="text-3xl font-bold">Disclaimer</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: June 2026</p>
      <div className="mt-8 space-y-6 text-muted-foreground">
        <p>
          Stories generated by Tiny Tales are created by an AI model and are for
          entertainment purposes only. Content is reviewed for safety but may occasionally
          be imperfect. Parental supervision is recommended for young children.
        </p>
      </div>
    </main>
  )
}
